WebApp/ViewModels/RestaurantViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace WebApp.ViewModels
{
    public class RestaurantViewModel
    {
        [Display(Name = "Name")]
        [Required, RegularExpression("[A-Z].*")]
        public string Name { get; set; }

        [Display(Name = "Zipcode")]
        [Required]
        public string ZipCode { get; set; }

        [Display(Name = "Address")]
        [Required]
        public string Street { get; set; }

        [Display(Name = "Cuisine")]
        [Required]
        public string Cuisine { get; set; }
        
    }
}

WebApp/Controllers/RestaurantsController.cs
using DL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly IReviewRepo _reviewRepo;

        public RestaurantsController(IReviewRepo reviewRepo)
        {
            _reviewRepo = reviewRepo;

        }
        // GET: Restaurant
        public ActionResult Index()
        {
            var restaurants = _reviewRepo.GetAllRestaurants().ToList();
            return View(restaurants);
        }

        // GET: Restaurants/Details/5
        [Route("Restaurants/Details/{name}")]
        
        public ActionResult Details(string name)
        {
            var restaurant = _reviewRepo.GetRestaurantObj(name);

          
            List<Models.Reviews> reviews = _reviewRepo.GetReviewsByRestaurantId(restaurant.Id);

            ViewData["ReviewsList"] = reviews;

            ViewData["RestaurantName"] = restaurant.Name;
            ViewData["RestaurantStreet"] = restaurant.Street;
            ViewData["RestaurantZipcode"] = restaurant.ZipCode;
            ViewData["RestaurantCuisine"] = restaurant.Cuisine;
            ViewData["RestaurantId"] = restaurant.Id;

            ViewBag.RestaurantNow = new Models.Restaurant()
            {
                Name = (string)ViewData["RestaurantName"],
                Street = (string)ViewData["RestaurantStreet"],
                ZipCode = (string)ViewData["RestaurantZipcode"],
                Cuisine = (string)ViewData["RestaurantCuisine"],
                Id = (int)ViewData["RestaurantId"],
            };

            return View(restaurant);
    }

        // GET: Restaurants/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RestaurantViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                var restaurant = new Models.Restaurant(viewModel.Name, viewModel.ZipCode, viewModel.Street, viewModel.Cuisine);
                _reviewRepo.CreateRestaurant(restaurant);

                TempData["CreatedRestaurant"] = restaurant.Name;
                Log.Debug("Restaurant creation successful!");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured creating a review restaurant");
                return View();
            }
        }


        // GET: Restaurants/Delete/5
        [Route("Restaurants/Delete/{id}")]
        public ActionResult Delete(string id)
        {
            var restaurant = _reviewRepo.GetAllRestaurants().First(x => x.Name == id);
            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost("Restaurants/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                _reviewRepo.DeleteRestaurant(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during Restaurant delete"); ;
                var restaurant = _reviewRepo.GetAllRestaurants().First(x => x.Name == id);
                return View(restaurant);
            }
        }
    }
}

WebApp/Controllers/ReviewsController.cs
using DL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ILogger<ReviewsController> _logger;
        private readonly IReviewRepo _reviewRepo;

        public ReviewsController(ILogger<ReviewsController> logger, IReviewRepo reviewRepo)
        {
            _logger = logger;
            _reviewRepo = reviewRepo;
        }


        // GET: Reviews
  
        [Route("Reviews/Index")]
        public ActionResult Index()
        {
            var reviews = _reviewRepo.GetAllReviews();
            return View(reviews);
        }

        // GET: Reviews/Details/5
        [Route("Reviews/Details/{id}")]
        public ActionResult Details(int id)
        {
            //var reviews = _reviewRepo.GetReviewsByRestaurantId(ViewBag.RestaurantNow.Id);

            //TempData["ReviewListById"] = reviews;

            return View(/*reviews*/);
        }

        // GET: Reviews/Create
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReviewsViewModel ViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(ViewModel);
                }

                int userId = ViewBag.UserNow.Id;

                int restaurantId = ViewBag.RestaurantNow.Id;

                var review = new Models.Reviews(ViewModel.Rating, ViewModel.Content, restaurantId, userId);
                _reviewRepo.CreateReview(review);

                TempData["CreatedReview"] = review.Id;
                Log.Debug("Review creation successful!" + TempData["CreatedReview"]);
                return RedirectToAction("Restaurants/Details/{restaurantId}");
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured creating a review");
                return View();
            }
        }

        // GET: Reviews/Edit/5
        [Route("Reviews/Edit/{id}")]
        public ActionResult Edit(int id)
        {
            var review = _reviewRepo.GetReviewObj(id);
            return View(review);
        }

        // GET: Reviews/Edit/5
        [HttpPost("Reviews/Edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Models.Reviews review, IFormCollection collection)
        {
            try
            {

                _reviewRepo.UpdateReview(id, review);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during Review edit");
                return View();
            }
        }

        // GET: Reviews/Delete/5
        [HttpPost("Reviews/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _reviewRepo.DeleteReview(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during Review delete");
                var review = _reviewRepo.GetAllReviews().First(x => x.Id == id);
                return View(review);
            }
        }
    }
}

WebApp/Views/Restaurants/Details.cshtml
@model Models.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<a class="nav-link" asp-area="" asp-controller="Reviews" asp-action="Create">Leave a review</a>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
    </dl>
</div>

<p class="ReviewsInRestaurant">
<p>
    <h4>Reviews</h4>
    <hr />
    <ul>
        @foreach (var review in ViewData["ReviewsList"] as List<Models.Reviews>)
        {
            <li>
                @review.Rating<br />

                @review.Content<br />

                @review.Date.ToShortDateString()<br />

            </li>
            <br />
            <br />

        }
    </ul>

    @{ var dataTest = ViewData["ReviewsList"] as List<Models.Reviews>; }
    @if (dataTest.Count == 0)
    {
        <a class="nav-link" asp-area="" asp-controller="Reviews" asp-action="Create">No reviews found. Be the first!</a>
    }

</p>
           
<div>

    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Restaurants/Index.cshtml
@model IEnumerable<Models.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<p>
    @if (TempData.ContainsKey("CreatedRestaurant"))
    {
        @:most recently created restaurant: @TempData.Peek("CreatedRestaurant")
    }
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuisine)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuisine)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {
                    id=item.Street,
                    name=item.Name
                }) |
            </td>
        </tr>
}
    </tbody>
</table>