WebApp/Controllers/RestaurantsController.cs
using DL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly IReviewRepo _reviewRepo;

        public RestaurantsController(IReviewRepo reviewRepo)
        {
            _reviewRepo = reviewRepo;

        }
        // GET: Restaurant
        public ActionResult Index()
        {
            var restaurants = _reviewRepo.GetAllRestaurants().ToList();
            return View(restaurants);
        }

        // GET: Restaurants/Details/5
        [Route("Restaurants/Details/{name}")]
        
        public ActionResult Details(string name)
        {
            var restaurant = _reviewRepo.GetRestaurantObj(name);

          
            List<Models.Reviews> reviews = _reviewRepo.GetReviewsByRestaurantId(restaurant.Id);

            ViewData["ReviewsList"] = reviews;

            ViewData["RestaurantName"] = restaurant.Name;
            ViewData["RestaurantStreet"] = restaurant.Street;
            ViewData["RestaurantZipcode"] = restaurant.ZipCode;
            ViewData["RestaurantCuisine"] = restaurant.Cuisine;
            ViewData["RestaurantId"] = restaurant.Id;

            ViewBag.RestaurantNow = new Models.Restaurant()
            {
                Name = (string)ViewData["RestaurantName"],
                Street = (string)ViewData["RestaurantStreet"],
                ZipCode = (string)ViewData["RestaurantZipcode"],
                Cuisine = (string)ViewData["RestaurantCuisine"],
                Id = (int)ViewData["RestaurantId"],
            };

            return View(restaurant);
    }

        // GET: Restaurants/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RestaurantViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                var restaurant = new Models.Restaurant(viewModel.Name, viewModel.ZipCode, viewModel.Street, viewModel.Cuisine);
                _reviewRepo.CreateRestaurant(restaurant);

                TempData["CreatedRestaurant"] = restaurant.Name;
                Log.Debug("Restaurant creation successful!");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured creating a review restaurant");
                return View();
            }
        }


        // GET: Restaurants/Delete/5
        [Route("Restaurants/Delete/{id}")]
        public ActionResult Delete(string id)
        {
            var restaurant = _reviewRepo.GetAllRestaurants().First(x => x.Name == id);
            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost("Restaurants/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                _reviewRepo.DeleteRestaurant(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during Restaurant delete"); ;
                var restaurant = _reviewRepo.GetAllRestaurants().First(x => x.Name == id);
                return View(restaurant);
            }
        }
    }
}

WebApp/Controllers/UsersController.cs
using DL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly DL.IReviewRepo _reviewRepo;

        public UsersController(DL.IReviewRepo reviewRepo)
        {
            _reviewRepo = reviewRepo;
        }
        // GET: Users
        [Route("Users/Index")]
        public ActionResult Index()
        {
            var users = _reviewRepo.GetAllUsers().ToList();
            return View(users);
        }

        // GET: Users/Details/5
        [Route("Users/Details/{id}")]
        public ActionResult Details(string id)
        {
            var users = _reviewRepo.GetAllUsers().First(u => u.Name == id);
            return View(users);
        }

        // GET: Users/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Home/Index");
                }

                var user = new Models.Users(viewModel.Name, viewModel.UserName, viewModel.Password, viewModel.Id);
                _reviewRepo.CreateUser(user);

                TempData["CreatedUser"] = user.Name;
                Log.Debug("User creation successful!" + user.Name);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during User create");
                return View();
            }
        }

        [Route("Users/Edit/{id}")]
        public ActionResult Edit(string id)
        {
            var user = _reviewRepo.GetUserObj(id);
            return View(user);
        }

        // GET: Users/Edit/5
        [HttpPost("Users/Edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Models.Users user, IFormCollection collection)
        {
            try
            {

                _reviewRepo.UpdateUser(id, user);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occuredduring User edit");
                return View(user);
            }
        }

        // GET: Users/Delete/5
        [Route("Users/Delete/{id}")]
        public ActionResult Delete(string id)
        {
            var users = _reviewRepo.GetAllUsers().First(x => x.Name == id);
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost("Users/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                _reviewRepo.DeleteRestaurant(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var error = new Exception();
                Log.Error(error, "An error has occured during User delete");
                var user = _reviewRepo.GetAllUsers().First(x => x.Name == id);
                return View(user);
            }
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EateryEvals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EateryEvals</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurant Lookup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            @if (!TempData.ContainsKey("LoggedInUser"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">Sign Up</a>
                            </li>
                        }
                            @if (TempData.ContainsKey("IsAdmin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Controlls</a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_ReviewsPartial.cshtml
@model Models.Reviews

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="ReviewPartialHead">
    <h3>@Model.Rating</h3>

    <h3>@Model.</h3>
</div>